feat: add initial samples and tests
googleapis/nodejs-apigee-registry pull request #2
Opened 2022-07-16 00:35 UTC by sofisl

2022-07-18 16:13 UTC, bcoe requested changes
Nit about the test.

2022-07-18 16:13 UTC, bcoe commented on samples/test/quickstart.js
> +    }, /9 FAILED_PRECONDITION: Invalid resource state for "�": Runtime instance not found for the project. Please ensure a runtime instance was provisioned for this project/);
There's a bad unicode character here, I would just simplify the assertion `FAILED_PREDONDITION`, Along with adding a tracking issue to create a better test in the future.

2022-07-18 19:59 UTC, sofisl commented on samples/test/quickstart.js
> +    }, /9 FAILED_PRECONDITION: Invalid resource state for "�": Runtime instance not found for the project. Please ensure a runtime instance was provisioned for this project/);
oops, thank you!

2022-07-19 21:36 UTC, bcoe approved these changes

2022-07-19 21:45 UTC, merged